name = "OMJulia"
uuid = "0f4fe800-344e-11e9-2949-fb537ad918e1"
authors = ["Martin Sj√∂lund <martin.sjolund@liu.se>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
ZMQ = "1"
